[tool.black]
line-length = 100
target-version = ['py39']
skip-string-normalization = true

[tool.isort]
known_first_party = 'app'
profile = 'black'
sections = 'FUTURE,STDLIB,THIRDPARTY,FIRSTPARTY,LOCALFOLDER'

[tool.pytest.ini_options]
testpaths = ['tests']
